### ISSUE TITLE
[BUG] app cannot be installed alongside amethyst

### ISSUE THREAD

**Issue by mister-monster** [retrnull/garnet#2]
**Describe the bug**

Will not install if amethyst is already installed due to conflicting signature but same app details.

**To Reproduce**
1. Ensure garnet is not on your system
2. Install Amethyst
3. Install garnet

**Comment by hundehausen** [comment]
I could not install it either with Obtainium, because of the same error.

**Comment by Final-Phoenix** [comment]
Same on my side

**Comment by franzaps** [comment]
The identifier needs to be updated. Is this not a priority?

**Comment by mister-monster** [comment]
@franzaps I'm sure the maintainers will get around to it, this is a brand new project and there's a lot going on. Monerujo integrated with a nostr client is a sizeable undertaking.

**Comment by franzaps** [comment]
@mister-monster nah, takes 10 seconds

**Comment by tim040404** [comment]
I am having this issue also, if I install Garnet after Amethyst it works, but then it keeps thinking Amethys is at version .30 and wants me to update which does nothing.

**Comment by Final-Phoenix** [comment]
https://bounties.monero.social/posts/147/garnet-maintenance-sync-upstream-new-icons-resolve-amethyst-dual-install-conflict-etc

**Comment by greensheeps** [comment]
https://github.com/retrnull/garnet/pull/10
Thanks @greenart7c3.
