### ISSUE TITLE
[ADJUSTMENT] XMR tip amounts

### ISSUE THREAD

**Issue by cod3cow** [retrnull/garnet#6]
The amounts of XMR tips are somehow to high IMHO and could be adjusted.

**Current values:** 
0.05 - 0.1 - 0.5

**Adjusted values e.g.:**
0.01 - 0.005 - 0.001

**Comment by Final-Phoenix** [comment]
Latest release v0.3.0 already did this

**Comment by retrnull** [comment]
As Final-Phoenix says, release v0.3.0 has lower values.
